--TEST--
test parsing
--FILE--
<?php
foreach (glob("jsonexamples/test_parsing/*.json") as $file) {
    $basename = basename($file);
    if (substr($basename, 0, 1) === 'i') {
        continue;
    }

    echo $basename . ": ";
    try {
        simdjson_decode(file_get_contents($file), true);
        echo "PASS : ";
    } catch (Exception $e) {
        echo "FAIL : ";
    }

    try {
        simdjson_decode_from_stream(fopen($file, "r"), true);
        echo "PASS";
    } catch (Exception $e) {
        echo "FAIL";
    }
    echo "\n";
}
--EXPECT--
n_array_1_true_without_comma.json: FAIL : FAIL
n_array_a_invalid_utf8.json: FAIL : FAIL
n_array_colon_instead_of_comma.json: FAIL : FAIL
n_array_comma_after_close.json: FAIL : FAIL
n_array_comma_and_number.json: FAIL : FAIL
n_array_double_comma.json: FAIL : FAIL
n_array_double_extra_comma.json: FAIL : FAIL
n_array_extra_close.json: FAIL : FAIL
n_array_extra_comma.json: FAIL : FAIL
n_array_incomplete.json: FAIL : FAIL
n_array_incomplete_invalid_value.json: FAIL : FAIL
n_array_inner_array_no_comma.json: FAIL : FAIL
n_array_invalid_utf8.json: FAIL : FAIL
n_array_items_separated_by_semicolon.json: FAIL : FAIL
n_array_just_comma.json: FAIL : FAIL
n_array_just_minus.json: FAIL : FAIL
n_array_missing_value.json: FAIL : FAIL
n_array_newlines_unclosed.json: FAIL : FAIL
n_array_number_and_comma.json: FAIL : FAIL
n_array_number_and_several_commas.json: FAIL : FAIL
n_array_spaces_vertical_tab_formfeed.json: FAIL : FAIL
n_array_star_inside.json: FAIL : FAIL
n_array_unclosed.json: FAIL : FAIL
n_array_unclosed_trailing_comma.json: FAIL : FAIL
n_array_unclosed_with_new_lines.json: FAIL : FAIL
n_array_unclosed_with_object_inside.json: FAIL : FAIL
n_incomplete_false.json: FAIL : FAIL
n_incomplete_null.json: FAIL : FAIL
n_incomplete_true.json: FAIL : FAIL
n_multidigit_number_then_00.json: FAIL : FAIL
n_number_++.json: FAIL : FAIL
n_number_+1.json: FAIL : FAIL
n_number_+Inf.json: FAIL : FAIL
n_number_-01.json: FAIL : FAIL
n_number_-1.0..json: FAIL : FAIL
n_number_-2..json: FAIL : FAIL
n_number_-NaN.json: FAIL : FAIL
n_number_.-1.json: FAIL : FAIL
n_number_.2e-3.json: FAIL : FAIL
n_number_0.1.2.json: FAIL : FAIL
n_number_0.3e+.json: FAIL : FAIL
n_number_0.3e.json: FAIL : FAIL
n_number_0.e1.json: FAIL : FAIL
n_number_0_capital_E+.json: FAIL : FAIL
n_number_0_capital_E.json: FAIL : FAIL
n_number_0e+.json: FAIL : FAIL
n_number_0e.json: FAIL : FAIL
n_number_1.0e+.json: FAIL : FAIL
n_number_1.0e-.json: FAIL : FAIL
n_number_1.0e.json: FAIL : FAIL
n_number_1_000.json: FAIL : FAIL
n_number_1eE2.json: FAIL : FAIL
n_number_2.e+3.json: FAIL : FAIL
n_number_2.e-3.json: FAIL : FAIL
n_number_2.e3.json: FAIL : FAIL
n_number_9.e+.json: FAIL : FAIL
n_number_Inf.json: FAIL : FAIL
n_number_NaN.json: FAIL : FAIL
n_number_U+FF11_fullwidth_digit_one.json: FAIL : FAIL
n_number_expression.json: FAIL : FAIL
n_number_hex_1_digit.json: FAIL : FAIL
n_number_hex_2_digits.json: FAIL : FAIL
n_number_infinity.json: FAIL : FAIL
n_number_invalid+-.json: FAIL : FAIL
n_number_invalid-negative-real.json: FAIL : FAIL
n_number_invalid-utf-8-in-bigger-int.json: FAIL : FAIL
n_number_invalid-utf-8-in-exponent.json: FAIL : FAIL
n_number_invalid-utf-8-in-int.json: FAIL : FAIL
n_number_minus_infinity.json: FAIL : FAIL
n_number_minus_sign_with_trailing_garbage.json: FAIL : FAIL
n_number_minus_space_1.json: FAIL : FAIL
n_number_neg_int_starting_with_zero.json: FAIL : FAIL
n_number_neg_real_without_int_part.json: FAIL : FAIL
n_number_neg_with_garbage_at_end.json: FAIL : FAIL
n_number_real_garbage_after_e.json: FAIL : FAIL
n_number_real_with_invalid_utf8_after_e.json: FAIL : FAIL
n_number_real_without_fractional_part.json: FAIL : FAIL
n_number_starting_with_dot.json: FAIL : FAIL
n_number_with_alpha.json: FAIL : FAIL
n_number_with_alpha_char.json: FAIL : FAIL
n_number_with_leading_zero.json: FAIL : FAIL
n_object_bad_value.json: FAIL : FAIL
n_object_bracket_key.json: FAIL : FAIL
n_object_comma_instead_of_colon.json: FAIL : FAIL
n_object_double_colon.json: FAIL : FAIL
n_object_emoji.json: FAIL : FAIL
n_object_garbage_at_end.json: FAIL : FAIL
n_object_key_with_single_quotes.json: FAIL : FAIL
n_object_lone_continuation_byte_in_key_and_trailing_comma.json: FAIL : FAIL
n_object_missing_colon.json: FAIL : FAIL
n_object_missing_key.json: FAIL : FAIL
n_object_missing_semicolon.json: FAIL : FAIL
n_object_missing_value.json: FAIL : FAIL
n_object_no-colon.json: FAIL : FAIL
n_object_non_string_key.json: FAIL : FAIL
n_object_non_string_key_but_huge_number_instead.json: FAIL : FAIL
n_object_repeated_null_null.json: FAIL : FAIL
n_object_several_trailing_commas.json: FAIL : FAIL
n_object_single_quote.json: FAIL : FAIL
n_object_trailing_comma.json: FAIL : FAIL
n_object_trailing_comment.json: FAIL : FAIL
n_object_trailing_comment_open.json: FAIL : FAIL
n_object_trailing_comment_slash_open.json: FAIL : FAIL
n_object_trailing_comment_slash_open_incomplete.json: FAIL : FAIL
n_object_two_commas_in_a_row.json: FAIL : FAIL
n_object_unquoted_key.json: FAIL : FAIL
n_object_unterminated-value.json: FAIL : FAIL
n_object_with_single_string.json: FAIL : FAIL
n_object_with_trailing_garbage.json: FAIL : FAIL
n_single_space.json: FAIL : FAIL
n_string_1_surrogate_then_escape.json: FAIL : FAIL
n_string_1_surrogate_then_escape_u.json: FAIL : FAIL
n_string_1_surrogate_then_escape_u1.json: FAIL : FAIL
n_string_1_surrogate_then_escape_u1x.json: FAIL : FAIL
n_string_accentuated_char_no_quotes.json: FAIL : FAIL
n_string_backslash_00.json: FAIL : FAIL
n_string_escape_x.json: FAIL : FAIL
n_string_escaped_backslash_bad.json: FAIL : FAIL
n_string_escaped_ctrl_char_tab.json: FAIL : FAIL
n_string_escaped_emoji.json: FAIL : FAIL
n_string_incomplete_escape.json: FAIL : FAIL
n_string_incomplete_escaped_character.json: FAIL : FAIL
n_string_incomplete_surrogate.json: FAIL : FAIL
n_string_incomplete_surrogate_escape_invalid.json: FAIL : FAIL
n_string_invalid-utf-8-in-escape.json: FAIL : FAIL
n_string_invalid_backslash_esc.json: FAIL : FAIL
n_string_invalid_unicode_escape.json: FAIL : FAIL
n_string_invalid_utf8_after_escape.json: FAIL : FAIL
n_string_leading_uescaped_thinspace.json: FAIL : FAIL
n_string_no_quotes_with_bad_escape.json: FAIL : FAIL
n_string_single_doublequote.json: FAIL : FAIL
n_string_single_quote.json: FAIL : FAIL
n_string_single_string_no_double_quotes.json: FAIL : FAIL
n_string_start_escape_unclosed.json: FAIL : FAIL
n_string_unescaped_crtl_char.json: FAIL : FAIL
n_string_unescaped_newline.json: FAIL : FAIL
n_string_unescaped_tab.json: FAIL : FAIL
n_string_unicode_CapitalU.json: FAIL : FAIL
n_string_with_trailing_garbage.json: FAIL : FAIL
n_structure_100000_opening_arrays.json: FAIL : FAIL
n_structure_U+2060_word_joined.json: FAIL : FAIL
n_structure_UTF8_BOM_no_data.json: FAIL : FAIL
n_structure_angle_bracket_..json: FAIL : FAIL
n_structure_angle_bracket_null.json: FAIL : FAIL
n_structure_array_trailing_garbage.json: FAIL : FAIL
n_structure_array_with_extra_array_close.json: FAIL : FAIL
n_structure_array_with_unclosed_string.json: FAIL : FAIL
n_structure_ascii-unicode-identifier.json: FAIL : FAIL
n_structure_capitalized_True.json: FAIL : FAIL
n_structure_close_unopened_array.json: FAIL : FAIL
n_structure_comma_instead_of_closing_brace.json: FAIL : FAIL
n_structure_double_array.json: FAIL : FAIL
n_structure_end_array.json: FAIL : FAIL
n_structure_incomplete_UTF8_BOM.json: FAIL : FAIL
n_structure_lone-invalid-utf-8.json: FAIL : FAIL
n_structure_lone-open-bracket.json: FAIL : FAIL
n_structure_no_data.json: FAIL : FAIL
n_structure_null-byte-outside-string.json: FAIL : FAIL
n_structure_number_with_trailing_garbage.json: FAIL : FAIL
n_structure_object_followed_by_closing_object.json: FAIL : FAIL
n_structure_object_unclosed_no_value.json: FAIL : FAIL
n_structure_object_with_comment.json: FAIL : FAIL
n_structure_object_with_trailing_garbage.json: FAIL : FAIL
n_structure_open_array_apostrophe.json: FAIL : FAIL
n_structure_open_array_comma.json: FAIL : FAIL
n_structure_open_array_object.json: FAIL : FAIL
n_structure_open_array_open_object.json: FAIL : FAIL
n_structure_open_array_open_string.json: FAIL : FAIL
n_structure_open_array_string.json: FAIL : FAIL
n_structure_open_object.json: FAIL : FAIL
n_structure_open_object_close_array.json: FAIL : FAIL
n_structure_open_object_comma.json: FAIL : FAIL
n_structure_open_object_open_array.json: FAIL : FAIL
n_structure_open_object_open_string.json: FAIL : FAIL
n_structure_open_object_string_with_apostrophes.json: FAIL : FAIL
n_structure_open_open.json: FAIL : FAIL
n_structure_single_eacute.json: FAIL : FAIL
n_structure_single_star.json: FAIL : FAIL
n_structure_trailing_#.json: FAIL : FAIL
n_structure_uescaped_LF_before_string.json: FAIL : FAIL
n_structure_unclosed_array.json: FAIL : FAIL
n_structure_unclosed_array_partial_null.json: FAIL : FAIL
n_structure_unclosed_array_unfinished_false.json: FAIL : FAIL
n_structure_unclosed_array_unfinished_true.json: FAIL : FAIL
n_structure_unclosed_object.json: FAIL : FAIL
n_structure_unicode-identifier.json: FAIL : FAIL
n_structure_whitespace_U+2060_word_joiner.json: FAIL : FAIL
n_structure_whitespace_formfeed.json: FAIL : FAIL
y_array_arraysWithSpaces.json: PASS : PASS
y_array_empty-string.json: PASS : PASS
y_array_empty.json: PASS : PASS
y_array_ending_with_newline.json: PASS : PASS
y_array_false.json: PASS : PASS
y_array_heterogeneous.json: PASS : PASS
y_array_null.json: PASS : PASS
y_array_with_1_and_newline.json: PASS : PASS
y_array_with_leading_space.json: PASS : PASS
y_array_with_several_null.json: PASS : PASS
y_array_with_trailing_space.json: PASS : PASS
y_number.json: PASS : PASS
y_number_0e+1.json: PASS : PASS
y_number_0e1.json: PASS : PASS
y_number_after_space.json: PASS : PASS
y_number_double_close_to_zero.json: PASS : PASS
y_number_int_with_exp.json: PASS : PASS
y_number_minus_zero.json: PASS : PASS
y_number_negative_int.json: PASS : PASS
y_number_negative_one.json: PASS : PASS
y_number_negative_zero.json: PASS : PASS
y_number_real_capital_e.json: PASS : PASS
y_number_real_capital_e_neg_exp.json: PASS : PASS
y_number_real_capital_e_pos_exp.json: PASS : PASS
y_number_real_exponent.json: PASS : PASS
y_number_real_fraction_exponent.json: PASS : PASS
y_number_real_neg_exp.json: PASS : PASS
y_number_real_pos_exponent.json: PASS : PASS
y_number_simple_int.json: PASS : PASS
y_number_simple_real.json: PASS : PASS
y_object.json: PASS : PASS
y_object_basic.json: PASS : PASS
y_object_duplicated_key.json: PASS : PASS
y_object_duplicated_key_and_value.json: PASS : PASS
y_object_empty.json: PASS : PASS
y_object_empty_key.json: PASS : PASS
y_object_escaped_null_in_key.json: PASS : PASS
y_object_extreme_numbers.json: PASS : PASS
y_object_long_strings.json: PASS : PASS
y_object_simple.json: PASS : PASS
y_object_string_unicode.json: PASS : PASS
y_object_with_newlines.json: PASS : PASS
y_string_1_2_3_bytes_UTF-8_sequences.json: PASS : PASS
y_string_accepted_surrogate_pair.json: PASS : PASS
y_string_accepted_surrogate_pairs.json: PASS : PASS
y_string_allowed_escapes.json: PASS : PASS
y_string_backslash_and_u_escaped_zero.json: PASS : PASS
y_string_backslash_doublequotes.json: PASS : PASS
y_string_comments.json: PASS : PASS
y_string_double_escape_a.json: PASS : PASS
y_string_double_escape_n.json: PASS : PASS
y_string_escaped_control_character.json: PASS : PASS
y_string_escaped_noncharacter.json: PASS : PASS
y_string_in_array.json: PASS : PASS
y_string_in_array_with_leading_space.json: PASS : PASS
y_string_last_surrogates_1_and_2.json: PASS : PASS
y_string_nbsp_uescaped.json: PASS : PASS
y_string_nonCharacterInUTF-8_U+10FFFF.json: PASS : PASS
y_string_nonCharacterInUTF-8_U+FFFF.json: PASS : PASS
y_string_null_escape.json: PASS : PASS
y_string_one-byte-utf-8.json: PASS : PASS
y_string_pi.json: PASS : PASS
y_string_reservedCharacterInUTF-8_U+1BFFF.json: PASS : PASS
y_string_simple_ascii.json: PASS : PASS
y_string_space.json: PASS : PASS
y_string_surrogates_U+1D11E_MUSICAL_SYMBOL_G_CLEF.json: PASS : PASS
y_string_three-byte-utf-8.json: PASS : PASS
y_string_two-byte-utf-8.json: PASS : PASS
y_string_u+2028_line_sep.json: PASS : PASS
y_string_u+2029_par_sep.json: PASS : PASS
y_string_uEscape.json: PASS : PASS
y_string_uescaped_newline.json: PASS : PASS
y_string_unescaped_char_delete.json: PASS : PASS
y_string_unicode.json: PASS : PASS
y_string_unicodeEscapedBackslash.json: PASS : PASS
y_string_unicode_2.json: PASS : PASS
y_string_unicode_U+10FFFE_nonchar.json: PASS : PASS
y_string_unicode_U+1FFFE_nonchar.json: PASS : PASS
y_string_unicode_U+200B_ZERO_WIDTH_SPACE.json: PASS : PASS
y_string_unicode_U+2064_invisible_plus.json: PASS : PASS
y_string_unicode_U+FDD0_nonchar.json: PASS : PASS
y_string_unicode_U+FFFE_nonchar.json: PASS : PASS
y_string_unicode_escaped_double_quote.json: PASS : PASS
y_string_utf8.json: PASS : PASS
y_string_with_del_character.json: PASS : PASS
y_structure_lonely_false.json: PASS : PASS
y_structure_lonely_int.json: PASS : PASS
y_structure_lonely_negative_real.json: PASS : PASS
y_structure_lonely_null.json: PASS : PASS
y_structure_lonely_string.json: PASS : PASS
y_structure_lonely_true.json: PASS : PASS
y_structure_string_empty.json: PASS : PASS
y_structure_trailing_newline.json: PASS : PASS
y_structure_true_in_array.json: PASS : PASS
y_structure_whitespace_array.json: PASS : PASS
